build: update release workflow to attempt to use versionize for auto-versioning
build: add important step of actually running Versionize

build: remove old versionize command flag

chore(release): 0.1.0

build: add missing action line

build: fix release name

feat(test): fake commit to test version bump

build: fix templating and use versionize for reading version

chore: delete bad changelog

chore: add .versionize config file

build: attempt to fix version step

chore(release): 0.1.0

fix(test): fake commit to test version bump

chore(release): 0.1.0

build: add debug dry run

chore(release): 0.1.0

build: potentially fix version commit issue

fix(test): fake commit to test version bump

chore(release): 0.1.0

build: hopefully fix tag name

fix(test): fake commit to test version bump

chore(release): 0.1.0

fix(test): please I'm desperate

chore(release): 0.1.0

fix(test): one last try

chore(release): 0.1.0

build: I swear if this is the issue I'mma be mad

fix(test): okay one more one last try

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,9 @@ jobs:
     steps:
       - uses: actions/checkout@v2
         with:
-          submodules: recursive
+          # submodules: recursive
+          fetch-depth: 0
+          fetch-tags: true
       - name: Setup .NET
         uses: actions/setup-dotnet@v1
         with:
@@ -23,31 +25,51 @@ jobs:
         run: |
           Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
           Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
+
+      - name: Setup git
+        run: |
+          git config --global user.name "Actions User"
+          git config --global user.email "actions@github.com"
+
+      - name: Install Versionize
+        run: dotnet tool install --global Versionize
+      - name: Versionize dry run
+        run: versionize --dry-run
+      - name: Versionize Release
+        id: versionize
+        run: versionize --exit-insignificant-commits
+        continue-on-error: true
+      - name: No release required
+        if: steps.versionize.outcome != 'success'
+        run: echo "Skipping Release. No release required."
+      - name: Retrieve version
+        id: version
+        shell: bash
+        run: |
+          echo "Retrieved version: $(versionize inspect)"
+          echo "VERSION=$(versionize inspect)" >> "$GITHUB_OUTPUT"
+
       - name: Build
+        if: steps.versionize.outcome == 'success'
         run: |
-          $ver = '${{ github.ref_name }}'
-          invoke-expression 'dotnet build --no-restore --configuration Release --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver'
-      - name: Write version into JSONs
-        run: |
-          $ver = '${{ github.ref_name }}'
-          $path = './AetherSenseRedux/bin/Release/AetherSenseRedux.json'
-          $json = Get-Content -Raw $path | ConvertFrom-Json
-          $json.AssemblyVersion = $ver
-          $content = $json | ConvertTo-Json
-          set-content -Path $path -Value $content
+          invoke-expression 'dotnet build --no-restore --configuration Release --nologo'
+
       - name: Archive
+        if: steps.versionize.outcome == 'success'
         run: Compress-Archive -Path AetherSenseRedux/bin/Release/* -DestinationPath AetherSenseRedux.zip
       - name: Upload a Build Artifact
+        if: steps.versionize.outcome == 'success'
         uses: actions/upload-artifact@v4.4.3
         with:
           path: |
             ./AetherSenseRedux/bin/Release/*
       - name: Create Release
+        if: steps.versionize.outcome == 'success'
         id: create_release
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: ${{ github.ref_name }}
-          name: AetherSenseRedux ${{ github.ref_name }}
+          tag_name: v${{ steps.version.outputs.VERSION }}
+          name: AetherSenseRedux ${{ steps.version.outputs.VERSION }}
           draft: false
           prerelease: false
           generate_release_notes: true
@@ -55,8 +77,9 @@ jobs:
             ./AetherSenseRedux.zip
 
       - name: Write out repo.json
+        if: steps.versionize.outcome == 'success'
         run: |
-          $ver = '${{ github.ref_name }}'
+          $ver = '${{ steps.version.outputs.VERSION }}'
           $path = './repo.json'
           $json = Get-Content -Raw $path | ConvertFrom-Json
           $json[0].AssemblyVersion = $ver
@@ -65,12 +88,8 @@ jobs:
           $content = $json | ConvertTo-Json -AsArray
           set-content -Path $path -Value $content
       - name: Commit repo.json
+        if: steps.versionize.outcome == 'success'
         run: |
-          git config --global user.name "Actions User"
-          git config --global user.email "actions@github.com"
-          git fetch origin main
-          git branch -f main ${{ github.sha }}
-          git checkout main
           git add repo.json
-          git commit -m "chore(ci): Updating repo.json for ${{ github.ref_name }}" || true
-          git push origin main
+          git commit --amend --no-edit || true
+          git push --follow-tags origin main
